const { setUpDatabase } = require('./setUp');
const { db } = require('../models/db');
const { getActions } = require('../models/action');

const staticActions = [
  {
    id: 'A1',
    description: 'Hold national campaign rally',
    type: 'hq',
    cost: 1000,
    budget_increase: 0,
    poll_increase: 5,
    required_systems: ['S4', 'S5', 'S9', 'S6', 'S10', 'S1', 'S2'],
    roles: ['Candidate'],
  },
  {
    id: 'A2',
    description: 'Hold local campaign rally',
    type: 'local',
    cost: 800,
    budget_increase: 0,
    poll_increase: 4,
    required_systems: ['S8', 'S9', 'S7', 'S10'],
    roles: ['Local Branch Manager'],
  },
  {
    id: 'A3',
    description: 'Conduct national GOTV activity',
    type: 'hq',
    cost: 600,
    budget_increase: 0,
    poll_increase: 3,
    required_systems: ['S4', 'S5', 'S6'],
    roles: ['HQ Campaign Team'],
  },
  {
    id: 'A4',
    description: 'Conduct local GOTV activity',
    type: 'local',
    cost: 600,
    budget_increase: 0,
    poll_increase: 3,
    required_systems: ['S8', 'S9', 'S10'],
    roles: ['Local Campaign Volunteers'],
  },
  {
    id: 'A5',
    description: 'Purchase campaign advertisement',
    type: 'hq',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S5'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A6',
    description: 'Purchase campaign advertisement',
    type: 'local',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S9'],
    roles: ['Local Communications Team'],
  },
  {
    id: 'A7',
    description: 'Enhance party website',
    type: 'hq',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S1', 'S5'],
    roles: ['HQ IT Team'],
  },
  {
    id: 'A8',
    description: 'Send email to appeal for donations',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S4', 'S5'],
    roles: ['Candidate'],
  },
  {
    id: 'A9',
    description: 'Send WhatsApp messages',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S4', 'S6'],
    roles: ['HQ Campaign Team'],
  },
  {
    id: 'A10',
    description: 'Send WhatsApp messages',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S8', 'S10'],
    roles: ['Local Campaign Volunteers'],
  },
  {
    id: 'A11',
    description: 'Share Facebook posts from computers',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S2', 'S5'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A12',
    description: 'Share Facebook posts from phones',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S2', 'S6'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A13',
    description: 'Share Facebook posts from computers',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S7', 'S9'],
    roles: ['Local Branch Manager', 'Local Communications Team'],
  },
  {
    id: 'A14',
    description: 'Share Facebook posts from phones',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S7', 'S10'],
    roles: ['Local Branch Manager', 'Local Communications Team'],
  },
];

beforeAll(setUpDatabase);

test('action table should return with role names', async () => {
  const actionsFromDb = await getActions();
  expect(actionsFromDb).toMatchObject(staticActions);
});
