const dumyGame = {
  id: 'TestGame',
  state: 'PREPARATION',
  poll: 40,
  budget: 7000,
  started_at: null,
  paused: true,
  millis_taken_before_started: 0,
  prevented_injections: [],
  every_injection_checked: false,
};

const dumyInjections = [
  {
    injection_id: 'I1',
    game_id: 'TestGame',
  },
  {
    injection_id: 'I11',
    game_id: 'TestGame',
  },
];

const dumyGameMitigations = [
  {
    id: 1,
    game_id: 'TestGame',
    mitigation_id: 'M1',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 2,
    game_id: 'TestGame',
    mitigation_id: 'M1',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 3,
    game_id: 'TestGame',
    mitigation_id: 'M2',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 4,
    game_id: 'TestGame',
    mitigation_id: 'M2',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 5,
    game_id: 'TestGame',
    mitigation_id: 'M3',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 6,
    game_id: 'TestGame',
    mitigation_id: 'M3',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 7,
    game_id: 'TestGame',
    mitigation_id: 'M4',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 8,
    game_id: 'TestGame',
    mitigation_id: 'M5',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 9,
    game_id: 'TestGame',
    mitigation_id: 'M6',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 10,
    game_id: 'TestGame',
    mitigation_id: 'M7',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 11,
    game_id: 'TestGame',
    mitigation_id: 'M8',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 12,
    game_id: 'TestGame',
    mitigation_id: 'M9',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 13,
    game_id: 'TestGame',
    mitigation_id: 'M10',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 14,
    game_id: 'TestGame',
    mitigation_id: 'M11',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 15,
    game_id: 'TestGame',
    mitigation_id: 'M12',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 16,
    game_id: 'TestGame',
    mitigation_id: 'M12',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 17,
    game_id: 'TestGame',
    mitigation_id: 'M13',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 18,
    game_id: 'TestGame',
    mitigation_id: 'M13',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 19,
    game_id: 'TestGame',
    mitigation_id: 'M14',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 20,
    game_id: 'TestGame',
    mitigation_id: 'M15',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 21,
    game_id: 'TestGame',
    mitigation_id: 'M16',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 22,
    game_id: 'TestGame',
    mitigation_id: 'M17',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 23,
    game_id: 'TestGame',
    mitigation_id: 'M18',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 24,
    game_id: 'TestGame',
    mitigation_id: 'M19',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 25,
    game_id: 'TestGame',
    mitigation_id: 'M19',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 26,
    game_id: 'TestGame',
    mitigation_id: 'M20',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 27,
    game_id: 'TestGame',
    mitigation_id: 'M20',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 28,
    game_id: 'TestGame',
    mitigation_id: 'M21',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 29,
    game_id: 'TestGame',
    mitigation_id: 'M22',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 30,
    game_id: 'TestGame',
    mitigation_id: 'M23',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 31,
    game_id: 'TestGame',
    mitigation_id: 'M23',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 32,
    game_id: 'TestGame',
    mitigation_id: 'M24',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 33,
    game_id: 'TestGame',
    mitigation_id: 'M24',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 34,
    game_id: 'TestGame',
    mitigation_id: 'M25',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 35,
    game_id: 'TestGame',
    mitigation_id: 'M25',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 36,
    game_id: 'TestGame',
    mitigation_id: 'M26',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 37,
    game_id: 'TestGame',
    mitigation_id: 'M26',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 38,
    game_id: 'TestGame',
    mitigation_id: 'M27',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 39,
    game_id: 'TestGame',
    mitigation_id: 'M27',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 40,
    game_id: 'TestGame',
    mitigation_id: 'M28',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 41,
    game_id: 'TestGame',
    mitigation_id: 'M28',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 42,
    game_id: 'TestGame',
    mitigation_id: 'M29',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 43,
    game_id: 'TestGame',
    mitigation_id: 'M29',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 44,
    game_id: 'TestGame',
    mitigation_id: 'M30',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 45,
    game_id: 'TestGame',
    mitigation_id: 'M30',
    location: 'local',
    state: false,
    preparation: false,
  },
  {
    id: 46,
    game_id: 'TestGame',
    mitigation_id: 'M31',
    location: 'hq',
    state: false,
    preparation: false,
  },
  {
    id: 47,
    game_id: 'TestGame',
    mitigation_id: 'M31',
    location: 'local',
    state: false,
    preparation: false,
  },
];
const dumyGameSystems = [
  { id: 1, game_id: 'TestGame', system_id: 'S1', state: true },
  { id: 2, game_id: 'TestGame', system_id: 'S2', state: true },
  { id: 3, game_id: 'TestGame', system_id: 'S3', state: true },
  { id: 4, game_id: 'TestGame', system_id: 'S4', state: true },
  { id: 5, game_id: 'TestGame', system_id: 'S5', state: true },
  { id: 6, game_id: 'TestGame', system_id: 'S6', state: true },
  { id: 7, game_id: 'TestGame', system_id: 'S7', state: true },
  { id: 8, game_id: 'TestGame', system_id: 'S8', state: true },
  { id: 9, game_id: 'TestGame', system_id: 'S9', state: true },
  { id: 10, game_id: 'TestGame', system_id: 'S10', state: true },
  { id: 11, game_id: 'TestGame', system_id: 'S11', state: true },
  { id: 12, game_id: 'TestGame', system_id: 'S12', state: true },
];

const dumyLogs = null;

const staticActions = [
  {
    id: 'A1',
    description: 'Hold national campaign rally',
    type: 'hq',
    cost: 1000,
    budget_increase: 0,
    poll_increase: 5,
    required_systems: ['S4', 'S5', 'S9', 'S6', 'S10', 'S1', 'S2'],
    roles: ['Candidate'],
  },
  {
    id: 'A2',
    description: 'Hold local campaign rally',
    type: 'local',
    cost: 800,
    budget_increase: 0,
    poll_increase: 4,
    required_systems: ['S8', 'S9', 'S7', 'S10'],
    roles: ['Local Branch Manager'],
  },
  {
    id: 'A3',
    description: 'Conduct national GOTV activity',
    type: 'hq',
    cost: 600,
    budget_increase: 0,
    poll_increase: 3,
    required_systems: ['S4', 'S5', 'S6'],
    roles: ['HQ Campaign Team'],
  },
  {
    id: 'A4',
    description: 'Conduct local GOTV activity',
    type: 'local',
    cost: 600,
    budget_increase: 0,
    poll_increase: 3,
    required_systems: ['S8', 'S9', 'S10'],
    roles: ['Local Campaign Volunteers'],
  },
  {
    id: 'A5',
    description: 'Purchase campaign advertisement',
    type: 'hq',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S5'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A6',
    description: 'Purchase campaign advertisement',
    type: 'local',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S9'],
    roles: ['Local Communications Team'],
  },
  {
    id: 'A7',
    description: 'Enhance party website',
    type: 'hq',
    cost: 500,
    budget_increase: 0,
    poll_increase: 2,
    required_systems: ['S1', 'S5'],
    roles: ['HQ IT Team'],
  },
  {
    id: 'A8',
    description: 'Send email to appeal for donations',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S4', 'S5'],
    roles: ['Candidate'],
  },
  {
    id: 'A9',
    description: 'Send WhatsApp messages',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S4', 'S6'],
    roles: ['HQ Campaign Team'],
  },
  {
    id: 'A10',
    description: 'Send WhatsApp messages',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S8', 'S10'],
    roles: ['Local Campaign Volunteers'],
  },
  {
    id: 'A11',
    description: 'Share Facebook posts from computers',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S2', 'S5'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A12',
    description: 'Share Facebook posts from phones',
    type: 'hq',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S2', 'S6'],
    roles: ['HQ Campaign Manager', 'HQ Communications Team'],
  },
  {
    id: 'A13',
    description: 'Share Facebook posts from computers',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S7', 'S9'],
    roles: ['Local Branch Manager', 'Local Communications Team'],
  },
  {
    id: 'A14',
    description: 'Share Facebook posts from phones',
    type: 'local',
    cost: 0,
    budget_increase: 200,
    poll_increase: 0,
    required_systems: ['S7', 'S10'],
    roles: ['Local Branch Manager', 'Local Communications Team'],
  },
];

const staticCurveballs = [
  {
    id: 'C4',
    description: 'Disaster',
    budget_decrease: 1000,
    poll_decrease: 10,
  },
];

const staticInjections = [
  {
    id: 'I2',
    title: 'Databreach of Amazon',
    description: 'News of databreach of Amazon',
    trigger_time: 60000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - IT Team',
    asset_code: '2a',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP2',
        description: 'Add 2FA for Party Email',
        cost: null,
        location: 'hq',
        mitigation_type: 'hq',
        mitigation_id: 'M12',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I1',
    title: 'Local party staff switches parties',
    description: 'Local party staff switches parties',
    trigger_time: 120000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '1',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP1',
        description: 'Change office lock at LB',
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I4',
    title: 'Fake DB login page',
    description:
      'Fake DB login page - ask DB users to sign in for necessary campaign action',
    trigger_time: 180000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Campaign Team',
    asset_code: '3',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP3',
        description: 'Report phish',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I3',
    title: 'Databreach of Amazon',
    description: 'News of databreach of Amazon',
    trigger_time: 300000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Campaign Volunteer(s)',
    asset_code: '2b',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP29',
        description: 'Add 2FA for Party Email',
        cost: null,
        location: 'local',
        mitigation_type: 'local',
        mitigation_id: 'M12',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I5',
    title: 'Lyla Bowman switches parties',
    description:
      'National social media staffer Lyla Bowman (who had access to FB page) switches parties',
    trigger_time: 330000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Communications Team',
    asset_code: '5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP4',
        description: "Remove Lyla Bowman's HQ FB admin access",
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I6',
    title: 'Undetected password hack',
    description: 'Weak password guessed by hacker',
    trigger_time: 345000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '5.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I7',
    title: 'Spearphising message - HQ',
    description:
      'Spearphishing message attack from personal email of national candidate',
    trigger_time: 480000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - All Actors',
    asset_code: '6',
    skipper_mitigation: 'M14',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP3',
        description: 'Report phish',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I9',
    title: 'Office cleaning person leaves',
    description: 'Office cleaning person leaves',
    trigger_time: 630000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Party Campaign Manager',
    asset_code: '8',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP5',
        description: 'Change office lock at HQ',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I8',
    title: 'Spearphising message - LB',
    description:
      'Spearphishing message attack from personal email of national candidate',
    trigger_time: 630000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - All Actors',
    asset_code: '7',
    skipper_mitigation: 'M14',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP28',
        description: 'Report phish',
        cost: 1000,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I10',
    title: 'Undetected password hack',
    description:
      "Weak password of local social media manager's personal FB page guessed by hacker",
    trigger_time: 645000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '8.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I12',
    title: 'Phising email - Facebook',
    description: 'Facebook password reset phishing email',
    trigger_time: 750000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Communications Team',
    asset_code: '12',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP3',
        description: 'Report phish',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I11',
    title: 'Computers and hard drives stolen',
    description:
      'READ TO TABLE: Adversary walks into office & computers and hard drives stolen',
    trigger_time: 780000,
    location: 'local',
    type: 'Board',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '10',
    skipper_mitigation: 'M2',
    skipper_mitigation_type: 'local',
    systems_to_disable: ['S9'],
    poll_change: -1,
    responses: [
      {
        id: 'RP6',
        description: 'LB purchases new computers',
        cost: 500,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I13',
    title: 'Juran Knott leaves the party',
    description: 'Staff person with DB access, Juran Knott, leaves the party',
    trigger_time: 900000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - IT Team',
    asset_code: '14',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP7',
        description: "Remove Juran Knott's access to HQ Member DB",
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I14',
    title: 'Embarassing Facebook post',
    description: 'Embarrassing Facebook post sent during campaign',
    trigger_time: 1020000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '15',
    skipper_mitigation: 'M19',
    skipper_mitigation_type: 'party',
    systems_to_disable: [],
    poll_change: -0.5,
    responses: [
      {
        id: 'RP8',
        description: 'Add 2FA for Facebook',
        cost: null,
        location: 'hq',
        mitigation_type: 'hq',
        mitigation_id: 'M19',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I16',
    title: 'Spreadsheet phising attempt',
    description: 'Email received asking staff to download spreadsheet',
    trigger_time: 1020000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Campaign Volunteer(s)',
    asset_code: '16',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP28',
        description: 'Report phish',
        cost: 1000,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I15',
    title: 'News story - medium impact',
    description: 'News story - medium impact',
    trigger_time: 1140000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Communications Team',
    asset_code: '15m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -0.5,
    responses: null,
  },
  {
    id: 'I18',
    title: "Staff person Rodrigo Wintz' phone is stolen",
    description: "Staff person Rodrigo Wintz' phone is stolen",
    trigger_time: 1260000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - IT Team',
    asset_code: '18a',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP9',
        description: "Rodrigo Wintz' phone remotely wiped",
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I19',
    title: "Volunteer Julienne Marsh's phone is stolen",
    description: "Volunteer Julienne Marsh's phone is stolen",
    trigger_time: 1260000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Campaign Volunteer(s)',
    asset_code: '18b',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP10',
        description: "Julienne Marsh's phone remotely wiped",
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I17',
    title: 'BitTorrent download',
    description: 'Staff downloads bittorrent application',
    trigger_time: 1320000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '16.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I20',
    title: 'Former cleaner stole computers',
    description:
      'READ TO TABLE: Former cleaner accesses office & computers stolen',
    trigger_time: 1380000,
    location: 'hq',
    type: 'Board',
    recipient_role: 'HQ - Party Campaign Manager',
    asset_code: '19',
    skipper_mitigation: 'M3',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S5'],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP11',
        description: 'HQ purchases new computers',
        cost: 1000,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S5'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I21',
    title: 'Stolen voter DB used by opponent',
    description:
      'Computer is stolen & local excel DB of voters stolen and used by opponent',
    trigger_time: 1500000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - All Actors',
    asset_code: '20',
    skipper_mitigation: 'M28',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I23',
    title: 'News story - medium impact',
    description:
      'News story - medium impact: Sensitive party strategy stolen by opponent',
    trigger_time: 1560000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Party Campaign Manager',
    asset_code: '22a',
    skipper_mitigation: 'M12',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I27',
    title: 'Supporter list stolen',
    description: 'Supporter list stolen by opposition - used to swing voters',
    trigger_time: 1650000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Campaign Team',
    asset_code: '25',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I22',
    title: 'Alina Weaver leaves party',
    description: 'Local comms staff person Alina Weaver leaves party',
    trigger_time: 1680000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Communications Team',
    asset_code: '21',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP12',
        description: 'Remove Alina Weaver from WhatsApp group',
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I28',
    title: 'Undetected DB hack',
    description: 'Weak password of staffer with DB access guessed by hacker',
    trigger_time: 1710000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '25.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I29',
    title: 'News story - medium impact',
    description:
      'News story - medium impact: Supporters personal info leaked, causing supporters to lose trust in the party',
    trigger_time: 1770000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Campaign Team',
    asset_code: '26',
    skipper_mitigation: 'M5',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I24',
    title: 'News story - low impact',
    description:
      'News story - low impact: Local sensitive party strategy stolen by opponent',
    trigger_time: 1800000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '22b',
    skipper_mitigation: 'M12',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I30',
    title: 'News story - high impact',
    description:
      'News story - high impact: Private chats, emails, messages leaked',
    trigger_time: 1890000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - All Actors',
    asset_code: '27a',
    skipper_mitigation: 'M27',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I25',
    title: 'Local voters list stolen and wiped',
    description:
      'READ TO TABLE: Computers infected & local voters list and excel databases stolen and wiped by opponents',
    trigger_time: 1980000,
    location: 'local',
    type: 'Board',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '23',
    skipper_mitigation: 'M25',
    skipper_mitigation_type: 'local',
    systems_to_disable: ['S8'],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP13',
        description: 'Restore member files from backup',
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S8'],
        required_mitigation: 'M24',
        required_mitigation_type: 'local',
      },
      {
        id: 'RP14',
        description: 'Develop new voter list',
        cost: 750,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S8'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I32',
    title: 'Adversary stole computers',
    description:
      'READ TO TABLE: Adversary walks into office & steals computers',
    trigger_time: 2010000,
    location: 'hq',
    type: 'Board',
    recipient_role: 'HQ - Party Campaign Manager',
    asset_code: '28',
    skipper_mitigation: 'M2',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S5'],
    poll_change: -1,
    responses: [
      {
        id: 'RP11',
        description: 'HQ purchases new computers',
        cost: 1000,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S5'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I34',
    title: 'Marvin Chase changes party',
    description:
      'Staffer with Facebook account pwd, Marvin Chase, changes party',
    trigger_time: 2160000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Communications Team',
    asset_code: '30',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP16',
        description: 'Change Facebook account password',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I26',
    title: 'Staff person Simon Masnar loses phone',
    description: 'Staff person Simon Masnar loses phone',
    trigger_time: 2160000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Communications Team',
    asset_code: '24',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: [
      {
        id: 'RP15',
        description: "Simon Masnar's phone remotely wiped",
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I36',
    title: 'Facebook account suspended',
    description: 'READ TO TABLE: Facebook account suspended',
    trigger_time: 2400000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '32',
    skipper_mitigation: 'M21',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S2'],
    poll_change: -0.5,
    responses: [
      {
        id: 'RP17',
        description: 'Contact Facebook to restore account',
        cost: 0,
        location: 'party',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S2'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I31',
    title: 'News story - high impact',
    description:
      'News story - high impact: Private chats, emails, messages leaked',
    trigger_time: 2400000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - All Actors',
    asset_code: '27b',
    skipper_mitigation: 'M27',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I37',
    title: 'Email server compromised',
    description: 'Email server compromised',
    trigger_time: 2550000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '32.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I33',
    title: 'Former staff stole computers',
    description: 'READ TO TABLE: Former staff accesses office steals computers',
    trigger_time: 2580000,
    location: 'local',
    type: 'Board',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '29',
    skipper_mitigation: 'M3',
    skipper_mitigation_type: 'local',
    systems_to_disable: ['S9'],
    poll_change: -1,
    responses: [
      {
        id: 'RP6',
        description: 'LB purchases new computers',
        cost: 500,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I38',
    title: 'News story - high impact',
    description:
      'News story - high impact: All internal email conversations leaked',
    trigger_time: 2670000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Campaign Team',
    asset_code: '33a',
    skipper_mitigation: 'M11',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I41',
    title: 'Weak Facebook password guessed',
    description: 'Weak Facebook password guessed by hacker',
    trigger_time: 2790000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '34.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I35',
    title: 'News story - low impact',
    description:
      'News story - low impact: Conflicting messages between LB and HQ',
    trigger_time: 2820000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Communications Team',
    asset_code: '31',
    skipper_mitigation: 'M22',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -0.5,
    responses: null,
  },
  {
    id: 'I42',
    title: 'Harmful post on national Facebook account',
    description: 'Harmful posts go up on the national Facebook account',
    trigger_time: 2820000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '35',
    skipper_mitigation: 'M19',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1,
    responses: [
      {
        id: 'RP8',
        description: 'Add 2FA for Facebook',
        cost: null,
        location: 'hq',
        mitigation_type: 'hq',
        mitigation_id: 'M19',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I43',
    title: 'News story - medium impact',
    description: 'News story - medium impact',
    trigger_time: 2910000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Communications Team',
    asset_code: '35m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I44',
    title: 'DDOS attack on website',
    description: 'DDOS Attack occurs on website',
    trigger_time: 2940000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '35.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I47',
    title: 'News story - high impact',
    description:
      'News story - high impact: Embarrasing emails of candidate leaked (password was pulled from Amazon breach)',
    trigger_time: 3030000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - National Presidential Candidate',
    asset_code: '39a',
    skipper_mitigation: 'M12',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -0.5,
    responses: null,
  },
  {
    id: 'I39',
    title: 'News story - high impact',
    description:
      'News story - high impact: All internal email conversations leaked',
    trigger_time: 3060000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Communications Team',
    asset_code: '33b',
    skipper_mitigation: 'M11',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1,
    responses: null,
  },
  {
    id: 'I50',
    title: 'HQ members DB wiped',
    description: 'READ TO TABLE: HQ members database contents deleted',
    trigger_time: 3180000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '41',
    skipper_mitigation: 'M6',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S4'],
    poll_change: -1,
    responses: [
      {
        id: 'RP19',
        description: 'Access DB backup',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S4'],
        required_mitigation: 'M4',
        required_mitigation_type: 'hq',
      },
    ],
  },
  {
    id: 'I40',
    title: 'News story - medium impact',
    description:
      'News story - medium impact: WhatsApp chats screenshot and made public',
    trigger_time: 3270000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - National Presidential Candidate',
    asset_code: '34',
    skipper_mitigation: 'M23',
    skipper_mitigation_type: 'party',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I45',
    title: 'Adversary stole campaign strategy',
    description:
      'Adversary breaks into local office & steals hard copy of campaign strategy and outreach list',
    trigger_time: 3390000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Campaign Volunteer(s)',
    asset_code: '37',
    skipper_mitigation: 'M1',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I54',
    title: 'Embarassing message on website',
    description: 'Embarrasing message posted on website',
    trigger_time: 3390000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '43',
    skipper_mitigation: 'M8',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP21',
        description: 'Remove negative content',
        cost: 0,
        location: 'party',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I46',
    title: 'Office fire',
    description:
      'READ TO TABLE: Office fire destroys local computers & strategic voter lists lost',
    trigger_time: 3480000,
    location: 'local',
    type: 'Board',
    recipient_role: 'LB - All Actors',
    asset_code: '38',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: ['S8', 'S9'],
    poll_change: -2,
    responses: [
      {
        id: 'RP18',
        description: 'Create New Member Files',
        cost: 750,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S8'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP6',
        description: 'LB purchases new computers',
        cost: 500,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP13',
        description: 'Restore member files from backup',
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S8'],
        required_mitigation: 'M24',
        required_mitigation_type: 'local',
      },
    ],
  },
  {
    id: 'I55',
    title: 'News story - high impact',
    description: 'News story - high impact',
    trigger_time: 3480000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - All Actors',
    asset_code: '43m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I56',
    title: 'Ransomware attack',
    description: 'READ TO TABLE: Ransomware attack hits party computers',
    trigger_time: 3600000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '44a',
    skipper_mitigation: 'M29',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S5'],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP22',
        description: 'Pay ransomware',
        cost: 1500,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S5'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP11',
        description: 'HQ purchases new computers',
        cost: 1000,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S5'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP19',
        description: 'Access DB backup',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S4'],
        required_mitigation: 'M4',
        required_mitigation_type: 'hq',
      },
    ],
  },
  {
    id: 'I48',
    title: 'News story - low impact',
    description:
      'News story - low impact: Embarrasing emails of local campaign staff leaked (password was pulled from Amazon breach)',
    trigger_time: 3660000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '39b',
    skipper_mitigation: 'M12',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -0.5,
    responses: null,
  },
  {
    id: 'I61',
    title: 'National Facebook page taken down',
    description:
      'READ TO TABLE: National Party FB page taken down during critical campaign moment, unable to get message to your likely voters',
    trigger_time: 3780000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '46',
    skipper_mitigation: 'M21',
    skipper_mitigation_type: 'hq',
    systems_to_disable: ['S2'],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP24',
        description: 'Contact Facebook to restore HQ FB page',
        cost: 0,
        location: 'hq',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S2'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I51',
    title: 'Embarassing Facebook post',
    description: 'Embarrasing FB posts sent from party account',
    trigger_time: 3870000,
    location: 'local',
    type: 'Board',
    recipient_role: null,
    asset_code: '42',
    skipper_mitigation: 'M26',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -2,
    responses: [
      {
        id: 'RP20',
        description: "Take down posts and reset Local FB admins' passwords",
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I62',
    title: 'News story - low impact',
    description: 'News story - low impact',
    trigger_time: 3870000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - National Presidential Candidate',
    asset_code: '46m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -1.5,
    responses: null,
  },
  {
    id: 'I52',
    title: 'News story - high impact',
    description: 'News story - high impact',
    trigger_time: 3960000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '42m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -2,
    responses: null,
  },
  {
    id: 'I63',
    title: 'Adversary stole campaign strategy',
    description:
      'Adversary breaks into national office & Hard copy of campaign strategy and support lists stolen',
    trigger_time: 4080000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Party Campaign Manager',
    asset_code: '47',
    skipper_mitigation: 'M1',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -0.5,
    responses: null,
  },
  {
    id: 'I57',
    title: 'Ransomware attack',
    description: 'READ TO TABLE: Ransomware attack hits party computers',
    trigger_time: 4080000,
    location: 'local',
    type: 'Board',
    recipient_role: null,
    asset_code: '44b',
    skipper_mitigation: 'M29',
    skipper_mitigation_type: 'local',
    systems_to_disable: ['S8', 'S9'],
    poll_change: -1.5,
    responses: [
      {
        id: 'RP27',
        description: 'Pay ransomware',
        cost: 1000,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP6',
        description: 'LB purchases new computers',
        cost: 500,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S9'],
        required_mitigation: null,
        required_mitigation_type: null,
      },
      {
        id: 'RP13',
        description: 'Restore member files from backup',
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: ['S8'],
        required_mitigation: 'M24',
        required_mitigation_type: 'local',
      },
    ],
  },
  {
    id: 'I49',
    title: 'Phone infected',
    description: 'Phone infected via malicious app download',
    trigger_time: 4140000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '39.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I64',
    title: 'Embarassing message on website',
    description:
      'Embarrassing message posted on website day before election (website password duplicated and pulled from a data breach)',
    trigger_time: 4200000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '48',
    skipper_mitigation: 'M9',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -1,
    responses: [
      {
        id: 'RP25',
        description: "Add 2FA for Party Website and change admin's passwords",
        cost: null,
        location: 'party',
        mitigation_type: 'hq',
        mitigation_id: 'M9',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I65',
    title: 'News story - medium impact',
    description: 'News story - medium impact',
    trigger_time: 4260000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - IT Team',
    asset_code: '48m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I66',
    title: 'Weak Facebook password guessed',
    description:
      "Weak password of social media manager's personal FB page guessed by hacker",
    trigger_time: 4275000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '48.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I59',
    title: 'Harmful post on Facebook page',
    description:
      'Harmful posts go up on your local FB page, deterring voters on election day',
    trigger_time: 4320000,
    location: 'local',
    type: 'Board',
    recipient_role: null,
    asset_code: '45',
    skipper_mitigation: 'M19',
    skipper_mitigation_type: 'local',
    systems_to_disable: [],
    poll_change: -2,
    responses: [
      {
        id: 'RP23',
        description:
          "Change passwords for all LB FB admin's pages and remove content",
        cost: 0,
        location: 'local',
        mitigation_type: null,
        mitigation_id: null,
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I67',
    title: 'Harmful post on Facebook page',
    description:
      'Harmful posts go up on your national FB page, deterring voters on election day',
    trigger_time: 4350000,
    location: 'hq',
    type: 'Board',
    recipient_role: null,
    asset_code: '49',
    skipper_mitigation: 'M19',
    skipper_mitigation_type: 'hq',
    systems_to_disable: [],
    poll_change: -3,
    responses: [
      {
        id: 'RP26',
        description:
          "Add 2FA for National FB page admins' accounts and change passwords",
        cost: null,
        location: 'hq',
        mitigation_type: 'hq',
        mitigation_id: 'M19',
        systems_to_restore: null,
        required_mitigation: null,
        required_mitigation_type: null,
      },
    ],
  },
  {
    id: 'I68',
    title: 'News story - high impact',
    description: 'News story - high impact',
    trigger_time: 4410000,
    location: 'hq',
    type: 'Table',
    recipient_role: 'HQ - Campaign Team',
    asset_code: '49m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -3,
    responses: null,
  },
  {
    id: 'I60',
    title: 'News story - low impact',
    description: 'News story - low impact',
    trigger_time: 4410000,
    location: 'local',
    type: 'Table',
    recipient_role: 'LB - Party Branch Manager',
    asset_code: '45m',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: -2,
    responses: null,
  },
  {
    id: 'I53',
    title: 'Website hacked',
    description: 'Website hacked via unpatched operating system',
    trigger_time: 4680000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '42.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
  {
    id: 'I58',
    title: 'Weak Facebook password guessed',
    description:
      "Weak password of local social media manager's personal FB page guessed by hacker",
    trigger_time: 4920000,
    location: null,
    type: 'Background',
    recipient_role: null,
    asset_code: '44.5',
    skipper_mitigation: null,
    skipper_mitigation_type: null,
    systems_to_disable: [],
    poll_change: null,
    responses: null,
  },
];

module.exports = {
  dumyGame,
  dumyGameMitigations,
  dumyGameSystems,
  dumyInjections,
  dumyLogs,
  staticInjections,
  staticActions,
  staticCurveballs,
};
