module.exports = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CREATEGAME: 'createGame',
  JOINGAME: 'joinGame',
  GAMEUPDATED: 'gameUpdated',
  CHANGEMITIGATION: 'changeMitigation',
  PERFORMACTION: 'performAction',
  STARTSIMULATION: 'startSimulation',
  PAUSESIMULATION: 'pauseSimulation',
  FINISHSIMULATION: 'finishSimulation',
  RESTORESYSTEM: 'restoreSystem',
  DELIVEREINJECTION: 'delivereInjection',
  RESPONDTOINJECTION: 'respondToInjection',
  NONCORRECTRESPONDTOINJECTION: 'nonCorrectRespondToInjection',
};
